# See the Project README.md file for explanation of this Configuration file.
sensor_to_bmon_file: /home/cea/meter_db/meters.sqlite
logging_level: INFO
dry_run: False
file_sources:
  - pattern: /home/alan/chugach/*.csv
    reader: cea
    default_bmon: ahfc
    time_zone: US/Alaska
    file_retention: 3
    chunk_size: 200
  - pattern: /home/alan/mea/*.csv
    reader: mea
bmon_servers:
  ahfc:
    url: https://bms.ahfc.us/readingdb/reading/store/
    store_key: xyz
  mssd:
    url: https://bmon.matsuk12.us/readingdb/reading/store/
    store_key: def
