sensor_to_bmon_file: /home/cea/meter_db/meters.sqlite
logging_level: INFO
bmon_servers:
  ahfc:
    url: https://bms.ahfc.us/readingdb/reading/store/
    store_key: xyz
  an:
    url: https://bmon.analysisnorth.com/readingdb/reading/store/
    store_key: def
