meter_files: /home/cea/meters/*.csv
delete_after_process: True
meter_number_db: /home/cea/meter_db/meters.sqlite
logging_level: INFO
time_zone: US/Alaska
bmon_servers:
  ahfc:
    url: https://bms.ahfc.us/readingdb/reading/store/
    store_key: xyz
  an:
    url: https://bmon.analysisnorth.com/readingdb/reading/store/
    store_key: def
